### ISSUE TITLE
Some changes

### ISSUE THREAD

**Issue by pickfire** [phortx/Raspberry-Pi-Setup-Guide#3]
Hi, I would like to add more things to the guide.

There are 2 distribution of raspberry pi now, so downloads would be on www.archlinuxarm.org for the latest version of archlinux on raspberry pi:

```bash
# For Raspberry Pi 2
wget http://archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz
bsdtar -xpf ArchLinuxARM-rpi-2-latest.tar.gz -C root
sync

# For Raspberry Pi 1
wget http://archlinuxarm.org/os/ArchLinuxARM-rpi-latest.tar.gz
bsdtar -xpf ArchLinuxARM-rpi-latest.tar.gz -C root
sync
```

    sed -i "s/en_US.UTF-8/#en_US.UTF-8/" /etc/locale.conf # Without editing with nano

And I think you should change the *swappiness* to **1** with that much of swap as it will slow you computer.

    sed -i 's/#Color/Color/' /etc/pacman # Add color to pacman

Install the *needed* packages only:

    sudo pacman -S --needed nfs-utils htop openssh autofs alsa-utils alsa-firmware alsa-lib alsa-plugins git zsh zsh-grml-config base-devel diffutils libnewt

What is the [relog](https://github.com/phortx/Raspberry-Pi-Setup-Guide#10-zsh-and-dotfiles)?
What does `/dev/root  /  ext4  noatime,discard  0  0` mean?

I hope you can add more guide about installing an xorg-server and xf86-video-fbturbo-git. Thanks.

**Comment by phortx** [comment]
> Hi, I would like to add more things to the guide.

Nice, thank you :)

> What is the relog?
Login and Logout ;) Or just reboot the Pi

> What does `/dev/root / ext4 noatime,discard 0 0` mean?

That mounts the root filesystem to `/`, which has an ext4 filesystem. [noatime](https://wiki.archlinux.de/title/Noatime) increases the performance of write access slightly, `discard` should be used with SSDs and `TRIM`, `0 0` just means, that the partition should never be checked. You may change this.

> I hope you can add more guide about installing an xorg-server and xf86-video-fbturbo-git. Thanks.

Probably not, sorry. Since I'm using the pi complete headless. But I'm very glad to see merge requests with tutorials and stuff and I'd love to merge and publish them.


I'll merge the changes later or tomorrow. Thank your for your contribution.

**Comment by pickfire** [comment]
Use `hostnamectl set-hostname` instead of `nano /etc/hostname`.
